name-template: 'Apollo v$NEXT_MINOR_VERSION'
tag-template: 'apollo-v$NEXT_MINOR_VERSION'
version-template: 'apollo-v$MAJOR.$MINOR.$PATCH'
categories:
    - title: '🚀 New Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Changes & Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
        - 'changes'
    - title: '🧰 Maintenance'
      labels:
        - 'chore'
autolabeler:
    - label: 'enhancement'
      branch:
        - '/feature\/.+/'
      title:
        - '/add/i'
    - label: 'bug'
      branch:
        - '/fix\/.+/'
      title:
        - '/fix/i'
    - label: 'changes'
      title:
        - '/crash|remove|change/i'
    - label: 'chore'
      branch:
        - '/chore\/.+/'
      title:
        - '/chore/i'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&#@'
exclude-labels:
    - 'skip-changelog'
template: |
  $CHANGES
