name: Mars Release Drafter

on:
  push:
    branches: [ mars-release ]
  pull_request:
    branches: [ mars-release ]
  workflow_dispatch:

jobs:
  apollo_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        with:
          config-name: mars-release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GA_GITHUB_TOKEN }}